### ISSUE TITLE
Font name

### ISSUE THREAD

**Issue by sowizz** [juwanpetty/github-icons#2]
Hi, what font are you using in the preview?

**Comment by juwanpetty** [comment]
Hello! Mona Sans, released by GitHub late last year.
https://github.blog/2022-12-02-introducing-mona-sans-and-hubot-sans/

**Comment by sowizz** [comment]
Thank you. Those are sans fonts and do not have a monospace variant. Source code on previews looks like a monospaced fonts. Are you sure you're using Mona Sans as coding font?

**Comment by juwanpetty** [comment]
Oh sorry I thought you meant the font used in the graphic, not in the IDE. I'm using SF Mono from Apple, can be [found here](https://developer.apple.com/fonts/).

**Comment by sowizz** [comment]
Thank you again :)
